---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library("png")
library("knitr")
library("tiff")

```
```{r}
verticalImageCheck <- function(magnetogram){
    ncol_magnetogram <- ncol(magnetogram)
    nrow_magnetogram <- nrow(magnetogram)

    if (ncol_magnetogram < nrow_magnetogram) {
      retVal <- apply(magnetogram,1,rev)
    }
    else {
      retVal <- magnetogram
    }
    return(retVal)
}
```



```{r}

pngs <- read.table("~/txtFiles/pngsFinal.txt")
```
```{r}
i = 1

```

```{r}
image_import <- function(image,file_loc){
  readTIFF(paste0(file_loc,"/",image))
}

```


userOpinion0_1163 <- vector()

for (i in 1:116){
userOpinion0_1163[i] <- readline(prompt = "Is this image bright(1), good(0)")
  
}


```{r}
opinion1_291 = c(userOpinion0_1163,userOpinion117_209[117:208], userOpinion209_291)
```


```{r}
brightnessFirst291 <- 
read.csv("~/Magneto2020/DataCSV/pngTODOTesting.csv", header = TRUE, stringsAsFactors = FALSE)

above.8 <- vector()
total <- vector()
standard <- vector()
name <- vector()
path <- vector()
for (i in 1:291){
  name[i] <- brightnessFirst291$ImageName[i]
  path[i] <- brightnessFirst291$ImagePath[i]
  image <- image_import(name[i],path[i])
  
  above.8[i] <- length(which(image >= 0.80))
  total[i] <- length(image)
  standard[i] <- above.8[i]/total[i]
}
```

```{r}
xvals = 1:291
Images <- data.frame(standard, opinion1_291)
plot(x = xvals, y = Images$standard, col = Images$opinion1_291, ylim = c(0, 0.2))
legend(x = "bottomright", legend = paste0("image:", c("good", "bright")),
fill = c("black", "red"))
abline(v = 14)
```

```{r}
forlm <- data.frame(standard, opinion1_291)
forlm <- forlm[-192,]
lmod <- glm(opinion1_291 ~ standard, data = forlm, family = binomial)
summary(lmod)
plot(lmod, which = 1:6)
```
# Finding the McFadden Pseudo- $R^2$ Value

```{r}
nullmodel <- glm(opinion1_291~1, family = binomial,  data = forlm)

1-logLik(lmod)/logLik(nullmodel)
```

```{r}
coef <- lmod$coefficients
name <- "AGC--H-19260823-19260825.tif"
path <- "/home/ben/magneto/Images/AGC-H-19260101-19281230/"
image <- image_import(name,path)

 abovespec <- length(which(image >= 0.80))
  totalspec <- length(image)
  standardspec <- abovespec/totalspec
observation <- standardspec
decision <- exp(coef[1] + coef[2] * observation)/(1 + exp(coef[1] + coef[2] * observation))
decision
image <- verticalImageCheck(image)
image2 <- image

source("~/Magneto2020/Scripts/BreakoutOptimization.R")
WithGauss <-  t(apply(image, MARGIN = 1, FUN = deconvGauss, sig = 10, kern.trunc = 0.05, nw = 3 ))

#this is the defult for bright false
image2[image2 = NULL] <- 0
image2[image2 < (1 - mean(image2))] <- 0
    image2[image2 > 0] <- 1

#this is for bright is true  
image[image = NULL] <- 0
image[image < (quantile(image,0.91))] <- 0
image[image > 0] <- 1


#WithGauss2 <-  t(apply(image2, MARGIN = 1, FUN = deconvGauss, sig = 10, kern.trunc = 0.05, nw = 3 ))
#this was in there but doesnt do anything from what I can tell..
#WithGauss[0:100, ] <- mean(WithGauss)
 #  WithGauss[(nrow(WithGauss) - 60):(nrow(WithGauss)),] <- mean(WithGauss)
  # WithGauss[WithGauss < 0] <- 0
#WithGauss2[0:100, ] <- mean(WithGauss2)
 #  WithGauss2[(nrow(WithGauss2) - 60):(nrow(WithGauss2)),] <- mean(WithGauss2)
  # WithGauss2[WithGauss2 < 0] <- 0
plot(image)
plot(image2)
plot(WithGauss)

#plot(WithGauss2)
  
```



```{r}
Image <- 1/Image
      if(min(Image) == 1){
        Image <- Image - 1
        Image <- Image/max(Image)
}

Image[Image < (quantile(Image,0.90))] <- 0
      Image[Image > 0] <- 1

plot(Image)


      ## Identify Peaks +++++
      
      withGauss[0:100,] <- mean(withGauss)
      withGauss[(nrow(withGauss) - 60):(nrow(withGauss)),] <- mean(withGauss)
      withGauss[withGauss < 0] <- 0

      withGauss[withGauss < 0] <- 0
```

```{r}
saveRDS(opinion1_291, file = "~/Magneto2020/2006241-291opinionsB")
```
